# Generated by Django 6.0 on 2025-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=32)),
            ],
        ),
    ]
