# Generated by Django 6.0 on 2025-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=5)),
                ('User', models.IntegerField()),
                ('Amount', models.FloatField()),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=5)),
                ('User', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trades',
            fields=[
                ('TradeID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TID')),
                ('Ticker', models.CharField(max_length=5)),
                ('Type', models.BooleanField()),
                ('Amount', models.FloatField()),
                ('BuyPrice', models.FloatField()),
                ('SellPrice', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=5)),
                ('User', models.IntegerField()),
                ('Watchlist', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Balance',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='Password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='UID'),
        ),
    ]
