# Generated by Django 6.0 on 2026-02-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ideal',
        ),
        migrations.AlterField(
            model_name='user',
            name='risk_level',
            field=models.IntegerField(default=50),
        ),
    ]
