# Generated by Django 6.0 on 2025-12-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_assets_blacklist_trades_watchlist_user_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
