# Generated by Django 6.0 on 2025-12-14 17:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trades_user_alter_assets_user_alter_blacklist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
