# Generated by Django 6.0 on 2025-12-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trades_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='Ticker',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='Ticker',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='BuyPrice',
            new_name='buyPrice',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='Profit',
            new_name='profit',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='SellPrice',
            new_name='sellPrice',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='Ticker',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='TradeID',
            new_name='tradeID',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='Ticker',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='Watchlist',
            new_name='watchlist',
        ),
    ]
