# Generated by Django 6.0 on 2025-12-14 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_amount_assets_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('user', 'ticker')},
        ),
    ]
