# Generated by Django 6.0 on 2026-01-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='User',
            new_name='user',
        ),
    ]
