# Generated by Django 6.0 on 2026-01-19 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_trades_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchlist',
            new_name='watchlist_items',
        ),
    ]
