# Generated by Django 6.0 on 2026-01-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_watchlist_watchlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='buyPrice',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='sellPrice',
        ),
    ]
